apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anomaly-detection
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PhamNTSang/NT114.git
    path: anomaly-detection/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: anomaly-detection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
